[versions]
velocity = "3.4.0-SNAPSHOT"
configurate = "1.3.7"

[libraries]
velocity-api = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
configurate-lib = { group = "dev.dejvokep", name = "boosted-yaml", version.ref = "configurate" }
